<h3 align="left" style="color:blue">pandas</h3>

In [1]:
import pandas as pd
import numpy as np

#### DATAFRAMES (multi dimensional array)

#### 2. Load CSV to create dataframe

In [16]:
df=pd.read_csv("nba.csv")
print(df)

              Name            Team  Number Position  Age Height  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25    6-2     180
1      Jae Crowder  Boston Celtics      99       SF   25    6-6     235
2     John Holland  Boston Celtics      30       SG   27    6-5     205
3      R.J. Hunter  Boston Celtics      28       SG   22    6-5     185
4    Jonas Jerebko  Boston Celtics       8       PF   29   6-10     231
..             ...             ...     ...      ...  ...    ...     ...
452     Trey Lyles       Utah Jazz      41       PF   20   6-10     234
453   Shelvin Mack       Utah Jazz       8       PG   26    6-3     203
454      Raul Neto       Utah Jazz      25       PG   24    6-1     179
455   Tibor Pleiss       Utah Jazz      21        C   26    7-3     256
456    Jeff Withey       Utah Jazz      24        C   26    7-0     231

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
452           Kentucky  2239800.0
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0

[457 rows x 9 columns]

#### Operations

In [25]:
attendance = pd.Series(
    [132, 94, 112, 84, 254, 322, 472],
    index=[
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday",
    ],
)

revenue = attendance * 15
print("revenue:",revenue)
print("Sum of revenue:",revenue.sum())
print("Power of 2:",revenue**2)

revenue: Monday       1980
Tuesday      1410
Wednesday    1680
Thursday     1260
Friday       3810
Saturday     4830
Sunday       7080
dtype: int64
Sum of revenue: 22050
Power of 2: Monday        3920400
Tuesday       1988100
Wednesday     2822400
Thursday      1587600
Friday       14516100
Saturday     23328900
Sunday       50126400
dtype: int64

In [3]:
# DataFrame.aggregate(func, axis=0, *args, **kwargs)  
df.aggregate({'Age':['sum','min'], 'Salary':['max','min']})

         Age      Salary
sum  12311.0         NaN
min     19.0     30888.0
max      NaN  25000000.0

In [13]:
df.Age.min(),df.Age.max(),df.Age.mean(),df.Age.median(),df.Age.mode()

(19,
 40,
 26.938730853391686,
 26.0,
 0    24
 Name: Age, dtype: int64)

In [15]:
df[df.Position=='PG'].Age.min(),df[df.Position=='PG'].Age.max(),df[df.Position=='PG'].Age.mean(),df[df.Position=='PG'].Age.median(),df[df.Position=='PG'].Age.mode()

(20,
 40,
 26.847826086956523,
 26.5,
 0    24
 1    27
 Name: Age, dtype: int64)

In [7]:
df.Age.unique()

array([25, 27, 22, 29, 21, 24, 20, 26, 28, 32, 23, 30, 33, 34, 37, 36, 31,
       38, 39, 19, 35, 40], dtype=int64)

In [8]:
df.Age.value_counts()

Age
24    47
25    45
27    41
23    41
26    36
28    31
30    31
29    28
22    26
31    22
20    19
21    19
33    14
32    13
34    10
36    10
35     9
37     4
38     4
40     3
39     2
19     2
Name: count, dtype: int64

In [13]:
df.value_counts(['Age','Weight'])

Age  Weight
26   220       6
23   205       6
24   190       5
25   195       5
24   200       5
              ..
26   203       1
     206       1
     208       1
     215       1
40   250       1
Name: count, Length: 315, dtype: int64

In [26]:
df.value_counts(['Age','Weight'],normalize=True)           # normalize = proportion of value counts

Age  Weight
26   220       0.013129
23   205       0.013129
24   190       0.010941
25   195       0.010941
24   200       0.010941
                 ...
26   203       0.002188
     206       0.002188
     208       0.002188
     215       0.002188
40   250       0.002188
Name: proportion, Length: 315, dtype: float64

In [17]:
df.groupby('Team').mean(['Weight'])

                           Number        Age      Weight        Salary
Team
Atlanta Hawks           19.000000  28.200000  221.266667  4.860197e+06
Boston Celtics          31.866667  24.733333  219.466667  4.181505e+06
Brooklyn Nets           18.266667  25.600000  215.600000  3.501898e+06
Charlotte Hornets       17.133333  26.133333  220.400000  5.222728e+06
Chicago Bulls           19.200000  27.400000  218.933333  5.785559e+06
Cleveland Cavaliers     14.466667  29.533333  227.866667  7.642049e+06
Dallas Mavericks        20.000000  29.733333  227.000000  4.746582e+06
Denver Nuggets          15.266667  25.733333  217.533333  4.294424e+06
Detroit Pistons         17.266667  26.200000  222.200000  4.477884e+06
Golden State Warriors   20.866667  27.666667  224.600000  5.924600e+06
Houston Rockets         14.666667  26.866667  220.333333  5.018868e+06
Indiana Pacers          18.933333  26.400000  222.266667  4.450122e+06
Los Angeles Clippers    19.533333  29.466667  219.733333  6.323643e+06
Los Angeles Lakers      16.066667  27.533333  227.066667  4.784695e+06
Memphis Grizzlies       15.555556  28.388889  218.000000  5.467920e+06
Miami Heat              10.466667  28.933333  218.400000  6.347359e+06
Milwaukee Bucks         20.000000  24.562500  224.062500  4.350220e+06
Minnesota Timberwolves  19.571429  26.357143  228.642857  4.593054e+06
New Orleans Pelicans    17.000000  26.894737  221.000000  4.355304e+06
New York Knicks         13.250000  27.000000  223.625000  4.581494e+06
Oklahoma City Thunder   14.000000  27.066667  229.400000  6.251020e+06
Orlando Magic           16.428571  25.071429  213.357143  4.297248e+06
Philadelphia 76ers      18.066667  24.600000  222.133333  2.213778e+06
Phoenix Suns            15.466667  25.866667  218.600000  4.229676e+06
Portland Trail Blazers  16.000000  25.066667  218.600000  3.220121e+06
Sacramento Kings        16.933333  26.800000  221.333333  4.778911e+06
San Antonio Spurs       17.933333  31.600000  223.933333  5.629516e+06
Toronto Raptors         22.466667  26.133333  221.800000  4.741174e+06
Utah Jazz               17.866667  24.466667  220.000000  4.204006e+06
Washington Wizards      17.600000  27.866667  219.000000  5.088576e+06

In [20]:
pd.pivot_table(df, values="Weight", index='Team', 
               columns=['Position'], aggfunc=np.mean)

C:\Users\rajes\AppData\Local\Temp\ipykernel_21824\1518806095.py:1: FutureWarning: The provided callable <function mean at 0x0000026FCF08CD60> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pd.pivot_table(df, values="Weight", index='Team',

Position,C,PF,PG,SF,SG
Team,,,,,
Atlanta Hawks,250.000000,239.500000,179.000000,210.500000,208.000000
Boston Celtics,250.333333,235.333333,193.750000,235.000000,206.250000
Brooklyn Nets,261.500000,219.500000,193.333333,NaN,208.833333
Charlotte Hornets,256.333333,244.000000,191.000000,232.000000,200.000000
Chicago Bulls,241.000000,240.000000,175.500000,212.500000,206.500000
Cleveland Cavaliers,257.666667,253.000000,196.333333,241.500000,213.400000
Dallas Mavericks,263.333333,240.500000,193.750000,215.000000,224.000000
Denver Nuggets,250.000000,231.500000,191.000000,208.333333,213.000000
Detroit Pistons,261.333333,237.500000,192.250000,222.500000,207.500000
Golden State Warriors,260.000000,251.500000,191.000000,224.000000,194.666667
Houston Rockets,245.000000,238.500000,192.500000,226.666667,199.000000
Indiana Pacers,242.500000,249.500000,192.000000,225.333333,203.500000
Los Angeles Clippers,257.500000,243.666667,186.666667,227.500000,193.333333
Los Angeles Lakers,263.333333,240.000000,196.333333,223.000000,175.000000
Memphis Grizzlies,255.000000,241.833333,178.000000,228.666667,214.000000
Miami Heat,265.000000,238.750000,177.500000,219.000000,202.000000
Milwaukee Bucks,257.000000,245.333333,200.250000,231.000000,210.250000
Minnesota Timberwolves,264.000000,241.750000,192.666667,221.666667,199.000000
New Orleans Pelicans,257.666667,241.000000,186.250000,220.000000,215.600000
New York Knicks,266.500000,237.500000,197.500000,222.500000,202.500000
Oklahoma City Thunder,250.000000,251.666667,192.500000,232.666667,213.250000
Orlando Magic,252.500000,236.250000,176.000000,200.000000,211.000000
Philadelphia 76ers,262.500000,239.000000,194.000000,212.500000,205.500000
Phoenix Suns,253.333333,235.000000,186.000000,228.000000,207.000000
Portland Trail Blazers,246.666667,241.666667,184.000000,215.000000,203.200000
Sacramento Kings,258.333333,229.000000,180.500000,230.750000,200.750000
San Antonio Spurs,256.250000,245.000000,190.000000,230.000000,203.500000
Toronto Raptors,240.000000,243.750000,195.000000,204.000000,217.500000
Utah Jazz,244.000000,242.333333,190.750000,219.333333,210.000000
Washington Wizards,244.000000,247.500000,192.500000,208.250000,210.000000